# Generated by Django 5.2.17 on 2026-09-21 21:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacidade')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaces/', verbose_name='imagem')),
                ('opening_time', models.TimeField(verbose_name='abertura')),
                ('closing_time', models.TimeField(verbose_name='fechamento')),
                ('min_cancel_hours', models.PositiveIntegerField(default=48, verbose_name='antecedência mínima para cancelar (h)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'espaço',
                'verbose_name_plural': 'espaços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('role', models.CharField(choices=[('resident', 'Morador'), ('staff', 'Gestão'), ('admin', 'Admin')], default='resident', max_length=20)),
                ('tower', models.CharField(blank=True, max_length=100, verbose_name='torre')),
                ('apartment', models.CharField(blank=True, max_length=20, verbose_name='apartamento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='início')),
                ('end_at', models.DateTimeField(verbose_name='fim')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('protocol', models.CharField(max_length=32, unique=True, verbose_name='protocolo')),
                ('guests_count', models.PositiveIntegerField(default=0, verbose_name='qtd. convidados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedules', to='app.reservation', verbose_name='reserva relacionada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='app.space', verbose_name='espaço')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='app.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'convidado',
                'verbose_name_plural': 'convidados',
            },
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'evento de reserva',
                'verbose_name_plural': 'eventos de reserva',
                'ordering': ['-created_at'],
            },
        ),
    ]
