# Generated by Django 5.2.17 on 2026-09-21 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bloco, torre, ala ou setor do condomínio.', max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('code', models.CharField(blank=True, help_text='Código curto opcional (ex.: BRISAS, A).', max_length=20, null=True, unique=True, verbose_name='código')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='app.block', verbose_name='Bloco'),
        ),
    ]
