# Generated by Django 5.2.17 on 2026-09-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_migrate_tower_to_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tower',
        ),
    ]
